### ISSUE TITLE
Not working because can't choose a supported service

### ISSUE THREAD

**Issue by beaubbe** [DeuxHuitHuit/multilingual_oembed_field#2]
The selected supported service does not seem to be saved and make the extension unusable.

**Comment by nitriques** [comment]
Just update oEmbed to 1.8.9 or newer and it will work (as per specified in the meta.xml file).

BUT, I've also added this check on install.

![image](https://cloud.githubusercontent.com/assets/771169/8383114/b64b9c54-1c05-11e5-9382-a7bb7061e8ee.png)

**Comment by nitriques** [comment]
Released in [1.0.1](https://github.com/DeuxHuitHuit/multilingual_oembed_field/releases/tag/1.0.1)
